## Better Outputs

### How to Strip Outputs and Execute Interactive Code in a Python Script


In [ ]:
!pip install strip-interactive

Have you ever seen a tutorial with an interactive Python code and wished to execute it in a Python script like above?

It might be time-consuming to delete all `>>>` symbols and remove all outputs, especially when the code is long. That is why I created strip-interactive.

In [3]:
from strip_interactive import run_interactive

code = """
>>> import numpy as np
>>> print(np.array([1,2,3]))
[1 2 3]
>>> print(np.array([4,5,6]))
[4 5 6]
"""

clean_code = run_interactive(code)

[1 2 3]
[4 5 6]



[Link to the article about strip-interactive](https://towardsdatascience.com/how-to-strip-outputs-and-execute-interactive-code-in-a-python-script-6d4c5da3beb0?sk=1db3d887884ad2429b9c78e1c72a2a4d).

[Link to strip-interactive](https://github.com/khuyentran1401/strip_interactive).

### Pyfiglet: Make Large and Unique Letters Out of Ordinary Text in Python

In [ ]:
!pip install pyfiglet

If you want to make large and unique letters out of ordinary text using Python, try pyfiglet. Below are some outputs of pyfiglet:

In [18]:
import pyfiglet
from termcolor import colored, cprint

out = pyfiglet.figlet_format("Hello")
print(out)

 _   _      _ _       
| | | | ___| | | ___  
| |_| |/ _ \ | |/ _ \ 
|  _  |  __/ | | (_) |
|_| |_|\___|_|_|\___/ 
                      



In [20]:
out = pyfiglet.figlet_format("Hello", font='slant')
print(out)

    __  __     ____    
   / / / /__  / / /___ 
  / /_/ / _ \/ / / __ \
 / __  /  __/ / / /_/ /
/_/ /_/\___/_/_/\____/ 
                       



In [21]:
cprint(pyfiglet.figlet_format('Hello', font='bell'), 'blue')

 __  __         .    .         
 |   |    ___   |    |     __. 
 |___|  .'   `  |    |   .'   \
 |   |  |----'  |    |   |    |
 /   /  `.___, /\__ /\__  `._.'
                               



This could be used as the welcome message for your Python package 🙂

[Link to pyfiglet](https://github.com/pwaller/pyfiglet).

[Link to termcolor](https://pypi.org/project/termcolor/).

### Python Fire: Generate a CLI for Any Python Objects in Two Lines of Code

In [ ]:
!pip install fire

Have you ever wanted to adjust the values of Python objects from the command line, but found it inconvenient to do so?  With Python Fire, you can easily generate a command-line interface for any Python object in just two lines of code.

To see how Python Fire works, let's look at an example. Start with creating file named `fire_example.py`:

In [2]:
%%writefile fire_example.py
import fire


def get_mean(numbers: list):
    return sum(numbers) / len(numbers)


def get_modulo(num1: int, num2: int):
    return num1 % num2


if __name__ == "__main__":
    fire.Fire()

Writing fire_example.py


Then run the following command on your terminal:

```bash
$ python fire_example.py get_mean "[1, 2, 3]"
```

In [3]:
!python fire_example.py get_mean "[1, 2, 3]"

2.0


```bash
$ python fire_example.py get_modulo --num1=3 --num2=2
```

In [4]:
!python fire_example.py get_modulo --num1=3 --num2=2

1


[Link to Python Fire](https://github.com/google/python-fire).

### Typer: Build a Command-Line Interface in a Few Lines of Code

In [ ]:
!pip install typer 

While Python Fire is easy to use, it doesn't provide much flexibility in terms of customization. Typer offers tools for building CLI applications in Python with a more explicit syntax. Typer also uses type annotations to validate user input.

To see how Typer works, let's look at an example. Start with creating file named `typer_example.py`:

In [3]:
%%writefile typer_example.py
import typer

app = typer.Typer()

@app.command()
def add_numbers(x: float, y: float):
    """Adds two numbers and prints the result."""
    result = x + y
    print(f"The sum of {x} and {y} is {result}.")

if __name__ == "__main__":
    app()


Writing typer_example.py


Then run the following command on your terminal:
```bash
$ python typer_example.py hello world
```
And you should see an output like below:

In [9]:
!python typer_example.py hello world

Usage: typer_example.py [OPTIONS] X Y
Try 'typer_example.py --help' for help.

Error: Invalid value for 'X': 'hello' is not a valid float.


You can see that when the input is not a valid float, Typer raised a `TypeError` with a helpful error message. 

Providing the valid inputs will give the following output:
```bash
$ python typer_example.py 3 2
```

In [10]:
!python typer_example.py 3 2

The sum of 3.0 and 2.0 is 5.0.


[Link to Typer](https://typer.tiangolo.com/).

[My full article about Typer](https://towardsdatascience.com/typer-build-powerful-clis-in-one-line-of-code-using-python-321d9aef3be8).

### Generate a Tree View with rich

In [ ]:
!pip install rich 

If you want to generate a tree view of a specific structure such as files in a directory, use rich.tree. rich also allows you to add color to each branch using brackets.

In [2]:
from rich.tree import Tree
from rich import print

tree = Tree("[cyan]My Project")
tree.add("[green]data")
tree.add("[blue]model")
src = tree.add("[red]src")
src.add("[red]process_data.py")
print(tree)

My Project
├── data
├── model
└── src
    └── process_data.py

[Link to rich](https://github.com/Textualize/rich/tree/aa7926c1431eebfb2ccaab9f3b63a4ac6cd8dfe6).

### latexify_py: Generates a LaTex Math Description From a Python Function

In [ ]:
!pip install latexify-py

Have you ever wanted to add math description for your Python function but found it time-consuming to do so? latexify_py allows you to add LaTex math description with only one decorator.

In [4]:
import math
import latexify

@latexify.with_latex
def solve(a, b, c):
    return (-b + math.sqrt(b**2 - 4*a*c)) / (2*a)

solve

<latexify.core.with_latex.<locals>._LatexifiedFunction at 0x108520f70>

In [7]:
@latexify.with_latex
def sinc(x):
    if x == 0:
        return 1
    else:
        return math.sin(x) / x

sinc

<latexify.core.with_latex.<locals>._LatexifiedFunction at 0x1089b8040>

[Link to latexify_py](https://github.com/google/latexify_py).

### ManimML: Create Animations of Common ML Concepts in Python

If you want to create animations and visualizations for common ML concepts in Python, try ManimML.

The GIF below is the visualization of Variational Autoencoder made by ManimML.

![](../img/VAEScene.gif)

[Link to ManimML](https://github.com/helblazer811/ManimML).

ManimML is built on top of [Manim](https://towardsdatascience.com/how-to-create-mathematical-animations-like-3blue1brown-using-python-f571fb9da3d1?sk=67f831edb7de3560020c2ea0296447cf).