## Better Outputs

### How to Strip Outputs and Execute Interactive Code in a Python Script


In [ ]:
!pip install strip-interactive

Have you ever seen a tutorial with an interactive Python code and wished to execute it in a Python script like above?

It might be time-consuming to delete all `>>>` symbols and remove all outputs, especially when the code is long. That is why I created strip-interactive.

In [3]:
from strip_interactive import run_interactive

code = """
>>> import numpy as np
>>> print(np.array([1,2,3]))
[1 2 3]
>>> print(np.array([4,5,6]))
[4 5 6]
"""

clean_code = run_interactive(code)

[1 2 3]
[4 5 6]



[Link to the article about strip-interactive](https://towardsdatascience.com/how-to-strip-outputs-and-execute-interactive-code-in-a-python-script-6d4c5da3beb0?sk=1db3d887884ad2429b9c78e1c72a2a4d).

[Link to strip-interactive](https://github.com/khuyentran1401/strip_interactive).

### rich.inspect: Produce a Beautiful Report on any Python Object

In [ ]:
!pip install rich 

If you want to quickly see which attributes and methods of a Python object are available, use rich’s `inspect` method.

rich’s `inspect` method allows you to create a beautiful report for any Python object, including a string.

In [6]:
from rich import inspect

print(inspect('hello', methods=True))

╭────────────────────────────────────── <class 'str'> ──────────────────────────────────────╮
│ str(object='') -> str                                                                     │
│ str(bytes_or_buffer[, encoding[, errors]]) -> str                                         │
│                                                                                           │
│ ╭───────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ 'hello'                                                                               │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│   capitalize = def capitalize(): Return a capitalized version of the string.              │
│     casefold = def casefold(): Return a version of the string suitable for caseless       │
│                comparisons.                                                               │
│       center = def center(width, fillchar=' ', /): Return a centered string of length     │
│                width.                                                                     │
│        count = def count(...) S.count(sub[, start[, end]]) -> int                         │
│       encode = def encode(encoding='utf-8', errors='strict'): Encode the string using the │
│                codec registered for encoding.                                             │
│     endswith = def endswith(...) S.endswith(suffix[, start[, end]]) -> bool               │
│   expandtabs = def expandtabs(tabsize=8): Return a copy where all tab characters are      │
│                expanded using spaces.                                                     │
│         find = def find(...) S.find(sub[, start[, end]]) -> int                           │
│       format = def format(...) S.format(*args, **kwargs) -> str                           │
│   format_map = def format_map(...) S.format_map(mapping) -> str                           │
│        index = def index(...) S.index(sub[, start[, end]]) -> int                         │
│      isalnum = def isalnum(): Return True if the string is an alpha-numeric string, False │
│                otherwise.                                                                 │
│      isalpha = def isalpha(): Return True if the string is an alphabetic string, False    │
│                otherwise.                                                                 │
│      isascii = def isascii(): Return True if all characters in the string are ASCII,      │
│                False otherwise.                                                           │
│    isdecimal = def isdecimal(): Return True if the string is a decimal string, False      │
│                otherwise.                                                                 │
│      isdigit = def isdigit(): Return True if the string is a digit string, False          │
│                otherwise.                                                                 │
│ isidentifier = def isidentifier(): Return True if the string is a valid Python            │
│                identifier, False otherwise.                                               │
│      islower = def islower(): Return True if the string is a lowercase string, False      │
│                otherwise.                                                                 │
│    isnumeric = def isnumeric(): Return True if the string is a numeric string, False      │
│                otherwise.                                                                 │
│  isprintable = def isprintable(): Return True if the string is printable, False           │
│                otherwise.                                                                 │
│      isspace = def isspace(): Return True if the string is a whitespace string, False     │
│                otherwise.                         

None


### Rich’s Console: Debug your Python Function in One Line of Code

In [ ]:
!pip install rich 

Sometimes, you might want to know which elements in the function created a certain output. Instead of printing every variable in the function, you can simply use Rich’s `Console` object to print both the output and all the variables in the function.

In [7]:
from rich import console
from rich.console import Console 
import pandas as pd 

console = Console()

data = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

def edit_data(data):
    var_1 = 45
    var_2 = 30
    var_3 = var_1 + var_2
    data['a'] = [var_1, var_2, var_3]
    console.log(data, log_locals=True)

edit_data(data)

[08:12:24]     a  b                                                          ]8;id=137856;file:///tmp/ipykernel_174022/1165738010.py\1165738010.py]8;;\:14
           0  45  4                                                                          
           1  30  5                                                                          
           2  75  6                                                                          
           ╭───── locals ─────╮                                                              
           │  data =     a  b │                                                              
           │         0  45  4 │                                                              
           │         1  30  5 │                                                              
           │         2  75  6 │                                                              
           │ var_1 = 45       │                                                              
           │ var_2 = 30       │                                                              
           │ var_3 = 75       │                                                              
           ╰──────────────────╯

[Link to my article about rich](https://towardsdatascience.com/rich-generate-rich-and-beautiful-text-in-the-terminal-with-python-541f39abf32e).

[Link to rich](https://github.com/willmcgugan/rich).

### loguru: Print Readable Traceback in Python


In [ ]:
!pip install loguru 

Sometimes, it is difficult to understand the traceback and to know which inputs cause the error. Is there a way that you can print a more readable traceback?

That is when loguru comes in handy. By adding decorator `logger.catch` to a function, loguru logger will print a more readable trackback and save the traceback to a separate file  like below


In [9]:
from sklearn.metrics import mean_squared_error
import numpy as np
from loguru import logger

logger.add("file_{time}.log", format="{time} {level} {message}")

@logger.catch
def evaluate_result(y_true: np.array, y_pred: np.array):
    mean_square_err = mean_squared_error(y_true, y_pred)
    root_mean_square_err = mean_square_err ** 0.5

y_true = np.array([1, 2, 3])
y_pred = np.array([1.5, 2.2])
evaluate_result(y_true, y_pred)

2021-09-12 08:13:20.710 | ERROR    | __main__:<module>:14 - An error has been caught in function '<module>', process 'MainProcess' (174022), thread 'MainThread' (139812013745984):
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x7f2884c85be0, file "/home/khuyen/book/venv/lib/python3.8/site-packages/ipykernel_launcher.py", lin...
           └ <function _run_code at 0x7f2884c680d0>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x7f2884c85be0, file "/home/khuyen

```bash
> File "/tmp/ipykernel_174022/1865479429.py", line 14, in <module>
    evaluate_result(y_true, y_pred)
    │               │       └ array([1.5, 2.2])
    │               └ array([1, 2, 3])
    └ <function evaluate_result at 0x7f279588f430>

  File "/tmp/ipykernel_174022/1865479429.py", line 9, in evaluate_result
    mean_square_err = mean_squared_error(y_true, y_pred)
                      │                  │       └ array([1.5, 2.2])
                      │                  └ array([1, 2, 3])
                      └ <function mean_squared_error at 0x7f27958bfca0>

  File "/home/khuyen/book/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ (array([1, 2, 3]), array([1.5, 2.2]))
           └ <function mean_squared_error at 0x7f27958bfb80>
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 335, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
            │       │                     └ <function _check_reg_targets at 0x7f27958b7af0>
            │       └ array([1.5, 2.2])
            └ array([1, 2, 3])
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 88, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
    │                       │       └ array([1.5, 2.2])
    │                       └ array([1, 2, 3])
    └ <function check_consistent_length at 0x7f279676e040>
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 319, in check_consistent_length
    raise ValueError("Found input variables with inconsistent numbers of"

ValueError: Found input variables with inconsistent numbers of samples: [3, 2]
```

[Link to loguru](https://github.com/Delgan/loguru). 

### Icrecream: Never use print() to debug again

In [ ]:
!pip install icecream

If you use print or log to debug your code, you might be confused about which line of code creates the output, especially when there are many outputs.

You might insert text to make it less confusing, but it is time-consuming.

In [1]:
from icecream import ic

def plus_one(num):
    return num + 1

print('output of plus_on with num = 1:', plus_one(1))
print('output of plus_on with num = 2:', plus_one(2))

output of plus_on with num = 1: 2
output of plus_on with num = 2: 3


Try icecream instead. Icrecream inspects itself and prints both its own arguments and the values of those arguments like below.

In [2]:
ic(plus_one(1))
ic(plus_one(2))

ic| plus_one(1): 2
ic| plus_one(2): 3


3

Output:
```bash  
ic| plus_one(1): 2
ic| plus_one(2): 3
```

[Link to icecream](https://github.com/gruns/icecream)

[Link to my article about icecream](https://towardsdatascience.com/stop-using-print-to-debug-in-python-use-icecream-instead-79e17b963fcc)

### Pyfiglet: Make Large and Unique Letters Out of Ordinary Text in Python

In [ ]:
!pip install pyfiglet

If you want to make large and unique letters out of ordinary text using Python, try pyfiglet. Below are some outputs of pyfiglet:

In [18]:
import pyfiglet
from termcolor import colored, cprint

out = pyfiglet.figlet_format("Hello")
print(out)

 _   _      _ _       
| | | | ___| | | ___  
| |_| |/ _ \ | |/ _ \ 
|  _  |  __/ | | (_) |
|_| |_|\___|_|_|\___/ 
                      



In [20]:
out = pyfiglet.figlet_format("Hello", font='slant')
print(out)

    __  __     ____    
   / / / /__  / / /___ 
  / /_/ / _ \/ / / __ \
 / __  /  __/ / / /_/ /
/_/ /_/\___/_/_/\____/ 
                       



In [21]:
cprint(pyfiglet.figlet_format('Hello', font='bell'), 'blue')

 __  __         .    .         
 |   |    ___   |    |     __. 
 |___|  .'   `  |    |   .'   \
 |   |  |----'  |    |   |    |
 /   /  `.___, /\__ /\__  `._.'
                               



This could be used as the welcome message for your Python package 🙂

[Link to pyfiglet](https://github.com/pwaller/pyfiglet).

[Link to termcolor](https://pypi.org/project/termcolor/).

### heartrate — Visualize the Execution of a Python Program in Real-Time

In [ ]:
!pip install heartrate 

If you want to visualize which lines are executed and how many times they are executed, try heartrate.

You only need to add two lines of code to use heartrate.

In [24]:
import heartrate 
heartrate.trace(browser=True)

def factorial(x):
    if x == 1:
        return 1
    else:
        return (x * factorial(x-1))


if __name__ == "__main__":
    num = 5
    print(f"The factorial of {num} is {factorial(num)}")

 * Serving Flask app 'heartrate.core' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off
The factorial of 5 is 120
Opening in existing browser session.


You should see something similar to the below when opening the browser:

![image](heartrate.png)

[Link to heartrate](https://github.com/alexmojaki/heartrate).