## Better Outputs

### How to Strip Outputs and Execute Interactive Code in a Python Script


In [ ]:
!pip install strip-interactive

Have you ever seen a tutorial with an interactive Python code and wished to execute it in a Python script like above?

It might be time-consuming to delete all `>>>` symbols and remove all outputs, especially when the code is long. That is why I created strip-interactive.

In [3]:
from strip_interactive import run_interactive

code = """
>>> import numpy as np
>>> print(np.array([1,2,3]))
[1 2 3]
>>> print(np.array([4,5,6]))
[4 5 6]
"""

clean_code = run_interactive(code)

[1 2 3]
[4 5 6]



[Link to the article about strip-interactive](https://towardsdatascience.com/how-to-strip-outputs-and-execute-interactive-code-in-a-python-script-6d4c5da3beb0?sk=1db3d887884ad2429b9c78e1c72a2a4d).

[Link to strip-interactive](https://github.com/khuyentran1401/strip_interactive).

### Pyfiglet: Make Large and Unique Letters Out of Ordinary Text in Python

In [ ]:
!pip install pyfiglet

If you want to make large and unique letters out of ordinary text using Python, try pyfiglet. Below are some outputs of pyfiglet:

In [18]:
import pyfiglet
from termcolor import colored, cprint

out = pyfiglet.figlet_format("Hello")
print(out)

 _   _      _ _       
| | | | ___| | | ___  
| |_| |/ _ \ | |/ _ \ 
|  _  |  __/ | | (_) |
|_| |_|\___|_|_|\___/ 
                      



In [20]:
out = pyfiglet.figlet_format("Hello", font='slant')
print(out)

    __  __     ____    
   / / / /__  / / /___ 
  / /_/ / _ \/ / / __ \
 / __  /  __/ / / /_/ /
/_/ /_/\___/_/_/\____/ 
                       



In [21]:
cprint(pyfiglet.figlet_format('Hello', font='bell'), 'blue')

 __  __         .    .         
 |   |    ___   |    |     __. 
 |___|  .'   `  |    |   .'   \
 |   |  |----'  |    |   |    |
 /   /  `.___, /\__ /\__  `._.'
                               



This could be used as the welcome message for your Python package 🙂

[Link to pyfiglet](https://github.com/pwaller/pyfiglet).

[Link to termcolor](https://pypi.org/project/termcolor/).

### Typer: Build a Command-Line Interface in a Few Lines of Code

In [ ]:
!pip install typer 

The last thing you want to happen is to have users dig into your code to run it. Is there a way that users can insert arguments into your code on the command line?

That is when Typer comes in handy. Typer allows you to build a command-line interface in a few lines of code based on Python-type hints.

For example, in a file named `typer_example`, write:

```python
import typer 

def process_data(data: str, version: int):
    print(f'Processing {data},' 
          f'version {version}')

if __name__ == '__main__':
    typer.run(process_data)
```

On your terminal, type:
```bash
python typer_example.py data 1
```
And you should see an output like below:

In [20]:
!python typer_example.py data 1

Processing data,version 1


[Link to Typer](https://typer.tiangolo.com/).

[My full article about Typer](https://towardsdatascience.com/typer-build-powerful-clis-in-one-line-of-code-using-python-321d9aef3be8).