## Get Elements

### random.choice: Get a Randomly Selected Element From a Python List

Besides getting a random number, you can also get a random element from a Python list using random. In the code below, “stay at home” was picked randomly from a list of options.

In [3]:
import random 

to_do_tonight = ['stay at home', 'attend party', 'do exercise']

random.choice(to_do_tonight)

'attend party'

In [6]:
l = [1, 2, 3]
l.pop()

3

### random.choices: Get Weighted Random Choices From a Python List

If you want to get a list of random elements from a specific list, use `random.choices`. This method also allows you to weigh the possibility for each value with the `weights` parameter.

In the code below, I use `random.choices` to get a list of 10 random values. 0 is two times more likely to be selected than 1 and is ten times more likely to be selected than 2. 

In [9]:
import random 

random.choices([0, 1, 2], weights=[10, 5, 1], k=10)

[0, 0, 1, 0, 0, 1, 1, 0, 0, 0]

### random.sample: Get Multiple Random Elements from a Python List

If you want to get n random elements from a list, use `random.sample`.

In [1]:
import random

random.seed(1)
nums = [1, 2, 3, 4, 5]
random_nums = random.sample(nums, 2)
random_nums

[2, 1]

### heapq: Find n Max Values of a Python List

If you want to extract n max values from a large Python list, using `heapq` will speed up the code.

In the code below, using heapq is more than 2 times faster than using sorting and indexing. Both methods try to find the max values of a list of 10000 items.


In [1]:
import heapq
import random
from timeit import timeit

random.seed(0)
l = random.sample(range(0, 10000), 10000)

def get_n_max_sorting(l: list, n: int):
    l = sorted(l, reverse=True)
    return l[:n]

def get_n_max_heapq(l: list, n: int):
    return heapq.nlargest(n, l)

In [2]:
expSize = 1000
n = 100
time_sorting = timeit("get_n_max_sorting(l, n)", number=expSize,
                        globals=globals())
time_heapq = timeit('get_n_max_heapq(l, n)', number=expSize,
                    globals=globals())

ratio = round(time_sorting/time_heapq, 3)
print(f'Run {expSize} experiments. Using heapq is {ratio} times'
' faster than using sorting')

Run 1000 experiments. Using heapq is 2.827 times faster than using sorting


In [1]:
list_data = list(range(1000000))
%time squared_list = [x**2 for x in list_data]
# Output: CPU times: user 150 ms, sys: 1.72 ms, total: 152 ms

CPU times: user 26.4 ms, sys: 7.96 ms, total: 34.3 ms
Wall time: 34.8 ms


In [2]:
import numpy as np

np_data = np.arange(1000000)
%time squared_np = np_data**2
# Output: CPU times: user 1.62 ms, sys: 965 µs, total: 2.59 ms

CPU times: user 9 ms, sys: 830 μs, total: 9.83 ms
Wall time: 1.59 ms


In [16]:
lst = [1, 2, 3]
lst.append(4)
lst.insert(0, 0)
print(lst)  # Output: [0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]


In [17]:
arr = np.array([1, 2, 3])
print(np.sin(arr))  # Output: [0.84147098 0.90929743 0.14112001]
print(arr + np.array([10, 20, 30]))  # Output: [11 22 33]

[0.84147098 0.90929743 0.14112001]
[11 22 33]


In [18]:
nested_list = [[1, 2], [3, 4], [5, 6]]
print(nested_list[1][0])  # Output: 3

3


In [19]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.shape)  # Output: (3, 2)
print(matrix[:, 1])  # Output: [2 4 6]

(3, 2)
[2 4 6]


In [20]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(data)
std_dev = np.std(data)
print(f"Mean: {mean}, Standard Deviation: {std_dev}")

Mean: 3.5, Standard Deviation: 1.707825127659933
